### ISSUE TITLE
Reset gantry angles?

### ISSUE THREAD

**Issue by fahadmp** [x2sky/Esapi_CreateQAPlan#2]
Is there a way to reset all the gantry angles to 180? I modified this part of the code `                // Define collimator, gantry and couch angles //
                Double gantryAng = currBm.ControlPoints.First().GantryAngle;
                Double collAng = currBm.ControlPoints.First().CollimatorAngle;
                Double couchAng = 0.0;
`
to

 `                // Define collimator, gantry and couch angles //
                Double gantryAng = 0.0;
                Double collAng = 0.0;
                Double couchAng = 0.0;
`
But does not work, any ideas?

**Comment by x2sky** [comment]
Fahad, in order to fix the gantry, i think you will have to force the beam creation in the code from arc to sliding window beam.
So, in CreateAndComputeQAPlan -> AddBeamToVerifPlan function:
verifBm = verifPln.AddVMATBeam(...) needs to be modified to verifPln.AddSlidingWindowBeam(...). Obviously, you need to change the inputs accordingly.

Good luck.
